Resources:
  CustomApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: CustomApiGateway

  CustomApiGatewayAuthorizer: 
    Type: AWS::ApiGateway::Authorizer
    Properties: 
      AuthorizerResultTtlInSeconds: 10
      RestApiId:
        Ref: CustomApiGateway
      IdentitySource: method.request.header.Authorization
      Name: CustomCognitoAuthorizer
      Type: COGNITO_USER_POOLS
      ProviderARNs: 
        - {"Fn::Join": ["", ["arn:aws:cognito-idp:", {Ref: "AWS::Region"}, ":", {Ref: "AWS::AccountId"}, ":userpool/", Ref: CognitoUserPool]]}
  
Outputs:
  CustomApiGatewayRestApiId:
    Value:
      Ref: CustomApiGateway
    Export:
      Name: CustomApiGateway-restApiId
  CustomApiGatewayRestApiRootResourceId:
    Value:
      Fn::GetAtt:
        - CustomApiGateway
        - RootResourceId
    Export:
      Name: CustomApiGateway-rootResourceId  
  CustomApiGatewayAuthorizerRef:
    Value:
      Ref: CustomApiGatewayAuthorizer
    Export:
      Name: CustomApiGatewayAuthorizer-ref