Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Beyond'
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: 'GS1'
          KeySchema:
            - AttributeName: 'GS1PK'
              KeyType: 'HASH'
            - AttributeName: 'GS1SK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'KEYS_ONLY'
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: 'ttl'
        Enabled: true
